apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-product-pv
  namespace: microservices
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mongo-product"